# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            GIS Programming
description:      'GIS Programming GEO 4938/6938 Spring 2017'
url:              https://josephaandreoli.github.io/gis-programming/
baseurl:          /gis-programming
email:            andreoli5978690@ufl.edu
feedbackurl:      https://docs.google.com/forms/d/e/1FAIpQLSdL6CeAOUqaJsxu2nOltW-HylvxDE__lDgR5D8D5dTHPD9gCw/viewform
author:
  name:           'Joe Andreoli'
  url:            http://geog.ufl.edu/grad-students/andreoli/

github:
  repo:           https://github.com/datacarpentry/semester-biology
  #               Be sure the 'Issues' feature is activated in 'Settings'
